name: YesG Claim Offline
on:
  push:
    branches: [main]
  schedule:
    - cron: '*/485 * * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: wget https://cheatgame.pro/education/dataairdrop/datayesg.txt; python yesg_offline_claim.py
